package model;
// default package
// Generated 2018/1/18 �U�� 02:05:11 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Arrays;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "Emp", schema = "dbo", catalog = "java")
public class Emp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer empid;
	private String empname;
	private Integer salary;
	private Character sex;
	private byte[] photo;
	private int deptid;

	public Emp() {
	}

	public Emp(int deptid) {
		this.deptid = deptid;
	}

	public Emp(String empname, Integer salary, Character sex, byte[] photo, int deptid) {
		this.empname = empname;
		this.salary = salary;
		this.sex = sex;
		this.photo = photo;
		this.deptid = deptid;
	}
	
	@Override
	public String toString() {
		return "Emp [empid=" + empid + ", empname=" + empname + ", salary=" + salary + ", sex=" + sex + ", photo="
				+ Arrays.toString(photo) + ", deptid=" + deptid + "]";
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "empid", unique = true, nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@Column(name = "empname", length = 10)
	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	@Column(name = "salary")
	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	@Column(name = "sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Column(name = "photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Column(name = "deptid", nullable = false)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

}
